# Marvish Chandra, Tech Company Comparisons
from ossaudiodev import SNDCTL_DSP_GETBLKSIZE
import yfinance as yf

class TechCompanies:
    def companyList():
        aapl = yf.Ticker("AAPL")
        print(aapl.info)
        msft = yf.Ticker("MSFT")
        print(msft.info)
        goog = yf.Ticker("GOOG")
        print(goog.info)
        googl = yf.Ticker("GOOGL")
        print(googl.info)
        amazon = yf.Ticker("AMZN")
        print(amazon.info)
        taiwansemiconductormaufacturing = yf.Ticker("TSM")
        print(taiwansemiconductormaufacturing.info)
        meta = yf.ticker("META")
        print(meta.info)
        tcehy = yf.ticker("TCEHY")
        print(tcehy.info)
        nvidia = yf.ticker("NVDA")
        print(nvidia.info)
        disney = yf.ticker("DIS")
        print(disney.info)
        broadcom = yf.ticker("AVGO")
        print(broadcom.info)
        oracle = yf.ticker("ORCL")
        print(oracle.info)
        ciscosystems = yf.ticker("CSCO")
        print(ciscosystems.info)
        accenture = yf.ticker("ACN")
        print(accenture.info)
        adobe = yf.ticker("ADBE")
        print(adobe.info)
        salesforce = yf.ticker("CRM")
        print(salesforce.info)
        texasinstruments = yf.ticker("TXN")
        print(texasinstruments.info)
        qualcomm = yf.ticker("QCOM")
        print(qualcomm.info)
        amd = yf.ticker("AMD")
        print(amd.info)
        meituan = yf.ticker("MPNGY")
        print(meituan.info)
        intel = yf.ticker("INTC")
        print(intel.info)
        prosusNV = yf.ticker("PROSY")
        print(prosusNV.info)
        intuit = yf.ticker("INTU")
        print(intuit.info)
        spGlobal = yf.ticker("SPGI")
        print(spGlobal.info)
        IBM = yf.ticker("IBM")
        print(IBM.info)
        BYD = yf.ticker("BYDDY")
        print(BYD.info)
        SAP = yf.ticker("SAP")
        print(SAP.info)
        SONY = yf.ticker("SONY")
        print(SONY.info)
        nippon_telegraph_telephone = yf.ticker("NTTYY")
        print(nippon_telegraph_telephone.info)
        netflix = yf.ticker("NFLX")
        print(netflix.info)
        JD = yf.ticker("JD")
        print(JD.info)
        servicenow = yf.ticker("NOW")
        print(servicenow.info)
        appliedmaterials = yf.ticker("AMAT")
        print(appliedmaterials.info)
        analogdevices = yf.ticker("ADI")
        print(analogdevices.info)
        infosys = yf.ticker("INFY")
        print(infosys.info)
        softbank = yf.ticker("SFTBY")
        print(softbank.info)
        cmegroup = yf.ticker("CME")
        print(cmegroup.info)
        naspers = yf.ticker("NPSNY")
        print(naspers.info)
        atlassian = yf.ticker("TEAM")
        print(atlassian.info)
        microntechnology = yf.ticker("MU")
        print(microntechnology.info)
        activisionblizzard = yf.ticker("ATVI")
        print(activisionblizzard)
        netease = yf.ticker("NTES")
        print(netease)
        illinois_tool_works = yf.ticker("NTES")
        print(illinois_tool_works.info)
        lamresearch = yf.ticker("LRCX")
        print(lamresearch.info)
        equinix = yf.ticker("EQIX")
        print(equinix.info)
        snowflake = yf.ticker("SNOW")
        print(snowflake.info)
        recruit = yf.ticker("RCRUY")
        print(recruit.info)
        palo_alto_networks = yf.ticker("PANW")
        print(palo_alto_networks.info)
        nintendo = yf.ticker("NTDOY")
        print(nintendo.info)
        thomas_reuters = yf.ticker("TRI")
        print(thomas_reuters.info)
        tokyo_electron = yf.ticker("TOELY")
        print(tokyo_electron.info)
        synopsys = yf.ticker("SNPS")
        print(synopsys.info)
        moodys = yf.ticker("MCO")
        print(moodys.info)
        relx = yf.ticker("RELX")
        print(relx.info)
        shin_etsu_chemical = yf.ticker("SHECY")
        print(shin_etsu_chemical.info)
        hitachi = yf.ticker("HTHIY")
        print(hitachi.info)
        vmware = yf.ticker("VMW")
        print(vmware.info)
        kla = yf.ticker("KLAC")
        print(kla.info)
        baidu = yf.ticker("BIDU")
        print(baidu.info)
        cadencedesignsystems = yf.ticker("CDNS")
        print(cadencedesignsystems.info)
        crowdstrike_holdings = yf.ticker("CRWD")
        print(crowdstrike_holdings.info)
        amphenol = yf.ticker("APH")
        print(amphenol.info)
        autodesk = yf.ticker("ADSK")
        print(autodesk.info)
        nxp_semiconductors = yf.ticker("NXPI")
        print(nxp_semiconductors.info)
        ropertechnologies = yf.ticker("ROP")
        print(ropertechnologies.info)
        workday = yf.ticker("WDAY")
        print(workday.info)
        motorolasolutions = yf.ticker("MSI")
        print(motorolasolutions.info)
        marvelltechnology = yf.ticker("MRVL")
        print(marvelltechnology.info)
        teconnectivity = yf.ticker("MRVL")
        print(teconnectivity.info)
        shopify = yf.ticker("SHOP")
        print(shopify.info)
        hoyacorporation = yf.ticker("HOCPY")
        print(hoyacorporation.info)
        fortinet = yf.ticker("FTNT")
        print(fortinet.info)
        muratamanufacturing = yf.ticker("MRAAY")
        print(muratamanufacturing.info)
        arista = yf.ticker("ANET")
        print(arista.info)
        xiaomi = yf.ticker("XIACY")
        print(xiaomi.info)
        msci = yf.ticker("MSCI")
        print(msci.info)
        microchiptechnology = yf.ticker("MCHP")
        print(microchiptechnology)
        digitalrealtytrust = yf.ticker("DLR")
        print(digitalrealtytrust.info)
        EA = yf.ticker("EA")
        print(EA.info)
        infineontechologies = yf.ticker("IFNNY")
        print(infineontechologies.info)
        cognizant = yf.ticker("CTSH")
        print(cognizant.info)
        canon = yf.ticker("CAJ")
        print(canon.info)
        datadog = yf.ticker("DDOG")
        print(datadog.info)
        HP = yf.ticker("HPQ")
        print(HP.info)
        globalfoundries = yf.ticker("GFS")
        print(globalfoundries.info)
        signaporetelecommunications = yf.ticker("SGAPY")
        print(signaporetelecommunications.info)
        sealimited = yf.ticker("SE")
        print(sealimited.info)
        chunghwatelecom = yf.ticker("CHT")
        print(chunghwatelecom.info)
        twitter = yf.ticker("TWTR")
        print(twitter.info)
        dell = yf.ticker("DELL")
        print(dell.info)
        keysighttechnologies = yf.ticker("KEYS")
        print(keysighttechnologies.info)
        onsemiconductor = yf.ticker("ON")
        print(onsemiconductor.info)
        nasdaq = yf.ticker("NDAQ")
        print(nasdaq.info)
        corning = yf.ticker("GLW")
        print(corning.info)
        wipro = yf.ticker("GLW")
        print(wipro.info)
        costargroup = yf.ticker("CSGP")
        print(costargroup.info)
        woltersfluwer = yf.ticker("WTKWY")
        print(woltersfluwer.info)
        fujifilm = yf.ticker("FUJIY")
        print(fujifilm.info)
        rockwellautomation = yf.ticker("ROK")
        print(rockwellautomation.info)
        nokia = yf.ticker("NOK")
        print(nokia.info)